import prisma from '../client';

export default async function specialization() {
  const specializations = await prisma.specialization.createMany({
    data: [
      { specialization: 'acupuncture' },
      { specialization: 'allergy-and-immunology' },
      { specialization: 'anesthesiology' },
      { specialization: 'angiology' },
      { specialization: 'cardiology' },
      { specialization: 'cardiovascular-surgery' },
      { specialization: 'hand-surgery' },
      { specialization: 'head-and-neck-surgery' },
      { specialization: 'digestive-tract-surgery' },
      { specialization: 'general-surgery' },
      { specialization: 'oncological-surgery' },
      { specialization: 'pediatric-surgery' },
      { specialization: 'plastic-surgery' },
      { specialization: 'thoracic-surgery' },
      { specialization: 'vascular-surgery' },
      { specialization: 'medical-clinic' },
      { specialization: 'coloproctology' },
      { specialization: 'dermatology' },
      { specialization: 'endocrinology-and-metabology' },
      { specialization: 'endoscopy' },
      { specialization: 'gastroenterology' },
      { specialization: 'medical-genetics' },
      { specialization: 'geriatrics' },
      { specialization: 'gynecology-and-obstetrics' },
      { specialization: 'hematology-and-hemotherapy' },
      { specialization: 'homeopathy' },
      { specialization: 'infectology' },
      { specialization: 'mastology' },
      { specialization: 'emergency-medicine' },
      { specialization: 'family-and-community-medicine' },
      { specialization: 'occupational-medicine' },
      { specialization: 'traffic-medicine' },
      { specialization: 'sports-medicine' },
      { specialization: 'physical-medicine-and-rehabilitation' },
      { specialization: 'intensive-care' },
      { specialization: 'forensic-medicine-and-medical-expertise' },
      { specialization: 'nuclear-medicine' },
      { specialization: 'preventive-and-social-medicine' },
      { specialization: 'nephrology' },
      { specialization: 'eurosurgery' },
      { specialization: 'eurology' },
      { specialization: 'nutrology' },
      { specialization: 'ophthalmology' },
      { specialization: 'clinical-oncology' },
      { specialization: 'orthopedics and-traumatology' },
      { specialization: 'otolaryngology' },
      { specialization: 'pathology' },
      { specialization: 'clinical-pathology-medicine' },
      { specialization: 'pediatrics' },
      { specialization: 'pneumology' },
      { specialization: 'psychiatry' },
      { specialization: 'radiology-and-diagnostic-imaging' },
      { specialization: 'radiotherapy' },
      { specialization: 'rheumatology' },
      { specialization: 'urology' },
    ],
  });

  console.log({ specializations });
}
